### PR TITLE
Add skin property

### PR DESCRIPTION
**Pull request by alinchican**
Please test. :)

### CODE REVIEW

**Comment by danmakenoise** [comment]
I'm thinking that all of these API matching props are going to add up pretty quickly. WDYT if we just add in something like `customProps` which would just be directly passed on to JW Player. That way, we can refactor out a lot of these things and allow people to modify anything they want on the player, without this library having to mirror JW Player completely.

**Comment by alinchican** [comment]
Sounds good! This library should be kept lightweight and with minimum maintenance.

**Comment by danmakenoise** [comment]
@alinchican sorry this took so long, take a look at this PR and let me know i this would work for you! https://github.com/micnews/react-jw-player/pull/17

**Comment by alinchican** [comment]
It didn't took too long. :) I was caught up with other stuff but I was going to commit a PR this week.

Looks ok, I was going to do the same thing.

Thank you!!

**Pull request closed without merging**
