### PR TITLE
react & prop-types as peerDependencies, include react v16 as acceptable peerDep too

### LINKED ISSUE #59: React and prop-types should be peer dependencies
Making them explicit dependencies can lead to having multiple copies of these loaded. Particularly problematic for users who have upgraded to 16.

### PR DESCRIPTION
**Pull request by dustingibbs**
closes #59 

thanks!

### CODE REVIEW

**Comment by danmakenoise** [comment]
@dustingibbs looks good, just had a conflict with package.json, can you resolve?

**Comment by dustingibbs** [comment]
@danmakenoise looking at the conflict. I cannot resolve directly here as I don't have write access. It is pretty straight forward though.  Not sure why the conflict popped up you can see here:
```
<<<<<<< master
    "miclint": "^4.1.0",
    "prop-types": "^15.5.10",
    "react": "^15.4.1",
=======
>>>>>>> master
```

**Comment by danmakenoise** [comment]
You need to rebase your branch to the latest `master`

**Comment by dustingibbs** [comment]
@danmakenoise, sorry about that major brain fart. I had grabbed this repo while back, and didn't realize it had updated... It was very confusing to me until I realized that. Should be good to go now. Thanks

**Comment by kpdecker** [comment]
Thanks everyone!

**Pull request merged**
