### PR TITLE
Feature/additional time events

### PR DESCRIPTION
**Pull request by zentuit**
Our analytics group requested more granular stats than was possible in the existing `react-jw-player`. This PR adds ~3~ 2 additional time events

~- onStart : fired at the start of playing the video. This is fired only once so stopping and starting a video does not re-fire this event~ ... onPlay does this

- onTwentyFivePercent: fired at 25% mark

- onSeventyFivePercent: fired at 75% mark

### CODE REVIEW

**Comment by danmakenoise** [comment]
I'm good with implementing the two new percentages, but would prefer if we could find a way to tap into JW Player's native event hook for start, rather than at 1 second. Would you want to tackle that here?

**Comment by danmakenoise** [comment]
We might be able to modify the logic here a bit? https://github.com/micnews/react-jw-player/blob/master/src/create-event-handlers/on-play.js#L2

**Comment by zentuit** [comment]
Sure, I'll take a look.

**Comment by zentuit** [comment]
The 1 second check is unnecessary. `react-js-player`'s `onPlay` event only fires once. I must have confused it with the `jwplayer`'s onPlay (which is fired multiple times).

I'll simply remove the 1 second check.

**Comment by zentuit** [comment]
"simply remove the 1 second check" -- 4 commits later...

Now the PR only has the 25% and 75% events added.

**Comment by danmakenoise** [comment]
Awesome LGTM thank you!

**Pull request merged**
