### PR TITLE
Added support for multiple player scripts loading

### PR DESCRIPTION
**Pull request by nirarazi**
As a user of this component I would like to be able to load different playerIds on the client side, and would like each player's configuration to apply each time.
The changes in this PR allow that.

### CODE REVIEW

**Comment by nirarazi** [comment]
@danmakenoise I'm trying to make it work when there is more than a single player configuration. Before this change, after initially setting up the first config, all the subsequent videos will be played using this config, which is incorrect. My PR caches the configs by the player ID, and switches the `window.jwplayer.defaults` accordingly whenever a new player instance is initialized.
In my testing it had no issues, but can admit I didn't test it with multiple players on the same page. Would be interesting to test this scenario. Let me know about you thoughts around this.

**Comment by danmakenoise** [comment]
@nirarazi The only thing that makes me nervous about this is the external state management with `window.jwplayer.defaults` and relying on that to be consistent per configuration load, especially since it happens asynchronously from this code.

1. Is it possible to just store your player configs in an object and pass them to `customProps` on the player, rather than loading a different sdk script? That is how we handle different player configs, but we may be unique in that approach.

2. Is there anyway at all to accomplish this same behavior in your PR without having react-jw-player handle it? Maybe with some small tweaks to this library we could come up with a way to allow that.

3. Do you know of anyway to extract the player config from the hosted scripts without relying on `window.jwplayer.defaults`? I'm considering going to them and feature requesting that we have access to a JSON object of the player config for each player we've configured in the CMS.

Just some thoughts, let me know what you think!

**Comment by nirarazi** [comment]
@danmakenoise I totally understand your nervousness. It is just that JW doesn't leave us much options here. I'll try to answer you questions:

1. Not really. Other people in the organisation, far from coders, are in charge of configuring the different players, to suite their business needs. We must take it "as is" and make sure the config is implemented correctly for each video+player combination.

1. We can maybe provide lifecycle hooks that allow access to the required information, but this will leave the component incorrectly handling player changes. Didn't think it was the right way to go for this component.

1. I've actually communicated with JW's support and they've ensured me that there is no other option. For some weird reason they keep the SDK and the config bundled in a single, unique Javascript file. An option for us would be to fetch the URL, get the string response, and parse out the config, without the SDK getting loaded again and again. Does that seem like a good way to go?

Generally, I think we cannot leave the component as it is now. As I've already mentioned, it is obviously incorrectly handling such very common scenario.

Thanks a lot for putting the time and thought into this.

Let me know what you think.

**Comment by nirarazi** [comment]
@danmakenoise further thought on my 3rd answer above made me realize that we also need to accommodate the fact that every player might be using a different version of a player. This means we have to use the bundled file as script and execute it. We might need a solution of the likes of jQuery's `$.noConflict()`, in which we will essentially cache every config and alias every SDK version.
No one said it would be easy... :)

**Comment by danmakenoise** [comment]
@nirarazi okay what's our urgency on this? If we want to get this merged in soon, I'd rather it be labeled experimental and be behind a flag so that it isn't the default behavior. 

Otherwise, v2 is in the works here #60 and the plan is to have a base component and a wrapper component that has toggles for things like this. We could find a way to add that on into v2. 

Let me know your timeline, and we can figure something out. I don't want this to block you from using the library.

**Comment by nirarazi** [comment]
@danmakenoise let's make it experimental as it currently affects our users' experience. Would be happy to switch to v2 when its ready and hopefully avoid this kind of "patchy" fix.
Thanks a lot for your consideration!

**Comment by danmakenoise** [comment]
@nirarazi okay, do you have bandwidth to put this behind a flag in this PR? If not, I can get to it over the next week.

**Comment by nirarazi** [comment]
@danmakenoise sorry for the delay, just had my first child's birth :)
I'm not sure how you would like this to be implemented, so would appreciate some guidance, or even better - your implementation, as soon as you can. Let me know. Thanks!

**Comment by nirarazi** [comment]
@danmakenoise any updates on this? Thanks!

**Comment by danmakenoise** [comment]
@nirarazi none yet, we don't yet have the resources to work on this or finishing out version 2. hopefully will see some movement this week.

**Comment by danmakenoise** [comment]
Closing in favor of https://github.com/micnews/react-jw-player/pull/71

**Pull request closed without merging**
